config/routes.rb
Cook1::Application.routes.draw do

  devise_for :users
  resources :caterings, :offices
  resources "contacts", only: [:new, :create]
  root 'welcome#index'
end

app/models/catering.rb
class Catering < ActiveRecord::Base
	has_many :offices
	validates :title, presence: true, length: { minimum: 5 }
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "your_email@example.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/office.rb
class Office < ActiveRecord::Base
	validates :title, presence: true, length: { minimum:5 }
  belongs_to :catering
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'simplex'
end

app/controllers/caterings_controller.rb
class CateringsController < ApplicationController
	def new
		@catering = Catering.new
	end

	def create
	  @catering = Catering.new(catering_params)
 
  	if @catering.save
    	redirect_to @catering
  	else
    	render 'new'
  	end
	end

	def show
		@catering = Catering.find(params[:id])
	end

	def index
		@caterings = Catering.all
	end

	def edit
		@catering = Catering.find(params[:id])
	end

	def update
		@catering = Catering.find(params[:id])

		if @catering.update(catering_params)
			redirect_to @catering
		else
			render 'edit'
		end
	end

	def destroy
		@catering = Catering.find(params[:id])
		@catering.destroy

		redirect_to caterings_path
	end

private
	def catering_params
		params.require(:catering).permit(:title, :adress, :phone, :email, :work_time, :minimum_order, :delivery_price, :description)
	end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
	def new
		@office = Office.new
	end

	def create
		@office = Office.new(office_params)

		if @office.save
			redirect_to @office
		else
			render 'new'
		end
	end

	def show
		@office = Office.find(params[:id])
	end

	def index
		@offices = Office.all
	end

	def edit
		@office = Office.find(params[:id])
	end

	def update
		@office = Office.find(params[:id])

		if @office.update(office_params)
			redirect_to @office
		else
			render 'edit'
		end
	end

	def destroy
		@office = Office.find(params[:id])
		@office.destroy

		redirect_to offices_path
	end

	private
		def office_params
			params.require(:office).permit(:title, :adress, :phone, :email, :description, :catering_id)
		end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  def facebook
    @user = User.find_for_facebook_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end

  def vkontakte
  	@user = User.find_for_vkontakte_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :nickname, :provider, :url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caterings_helper.rb
module CateringsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/caterings/_form.html.erb
<%= form_for @catering do |f| %>
  <% if @catering.errors.any? %>
    
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Please fix: <%= pluralize(@catering.errors.count, "error") %></h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @catering.errors.full_messages.each do |msg| %>
            <li>
            <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

  <% end %>
	<p>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control input-sm' %>
  </p>

	<p>
    <%= f.label :adress %><br>
    <%= f.text_field :adress, class: 'form-control input-sm'  %>
  </p>

	<p>
    <%= f.label :phone %><br>
    <%= f.telephone_field :phone, class: 'form-control input-sm'  %>
  </p>

	<p>
    <%= f.label :email %><br>
    <%= f.email_field :email, class: 'form-control input-sm'  %>
  </p>

	<p>
    <%= f.label :work_time %><br>
    <%= f.text_area :work_time, class: 'form-control' %>
  </p>

	<p>
    <%= f.label :minimum_order %><br>
    <%= f.text_field :minimum_order, class: 'form-control input-sm'  %>
  </p>

	<p>
    <%= f.label :delivery_price %><br>
    <%= f.text_field :delivery_price, class: 'form-control input-sm'  %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </p>

  <p>
    <%= link_to "Cancel", caterings_path, class: 'btn btn-default'  %> 
    <%= f.submit 'Submit', :class => 'btn btn-success' %>
  </p>
<% end %>

app/views/caterings/_form.html.haml
.row
  .col-lg-6
    .well
      = form_for @catering do |f|
        - if @catering.errors.any?
          .panel.panel-primary
            .panel-heading
              %h3.panel-title
                Please fix: #{pluralize(@catering.errors.count, "error")}
            .panel-body
              %ul
                - @catering.errors.full_messages.each do |msg|
                  %li
                    = msg
        %fieldset
        .form-group
          = f.text_field :title, class: 'form-control', :placeholder => :title.capitalize
        .form-group
          = f.text_field :adress, class: 'form-control', :placeholder => :adress.capitalize
        .form-group
          = f.telephone_field :phone, class: 'form-control', :placeholder => :phone.capitalize
        .form-group
          = f.email_field :email, class: 'form-control', :placeholder => :email.capitalize
        .form-group
          = f.text_area :work_time, class: 'form-control', :placeholder => :work_time.capitalize
        .form-group
          = f.text_field :minimum_order, class: 'form-control', :placeholder => :minimum_order.capitalize
        .form-group
          = f.text_field :delivery_price, class: 'form-control', :placeholder => :delivery_price.capitalize
        .form-group
          = f.text_area :description, class: 'form-control', :placeholder => :description.capitalize
        .form-group
          = link_to "Cancel", caterings_path, class: 'btn btn-default'
          = f.submit 'Submit', :class => 'btn btn-success'

app/views/caterings/edit.html.erb
<h1>Editing caterer</h1>

<%= render 'form' %>

app/views/caterings/index.html.erb
<h1>All caterings</h1>
<p align="right"><%= link_to "Create new catering", new_catering_path, class: 'btn btn-success' %></p>

<table width="100%">
	<% @caterings.order("updated_at desc").each do |catering| %>
		<tr>
			<td>
				<table width="100%">
					<tr>
						<td>
							<h3><%= link_to catering.title, catering %></h3>
							<strong><%= catering.adress %></strong><br>
							<%= catering.phone %><br>
							<%= catering.email %>
						</td>
						<td align="right">
						<font size="2">
								Working hours: <%= catering.work_time %><br>
								Minimum order: <%= catering.minimum_order %> UAH<br>
								If no minimum order delivery price: <%= catering.delivery_price %>
						</font>
						</td>
						<td width="150" align="right">
							<%= link_to 'Edit', edit_catering_path(catering), class: 'btn btn-danger' %>
							<%= link_to 'Delete', catering_path(catering), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
						</td>
					</tr>
				</table>
				<br>
				<br>
			</td>
		</tr>
	<% end %>
</table>

app/views/caterings/new.html.erb
<h1>Add new catering</h1>

<%= render 'form' %>

app/views/caterings/show.html.erb
<h1>Catering "<%= @catering.title %>"</h1>

<p><strong>Adress:</strong>
<%= @catering.adress %>
</p>

<p><strong>Phone:</strong>
<%= @catering.phone %>
</p>

<p><strong>Email:</strong>
<%= @catering.email %>
</p>

<p><strong>Work time:</strong>
<%= @catering.work_time %>
</p>

<p><strong>Minimum order:</strong>
<%= @catering.minimum_order %>
</p>

<p><strong>Delivery price:</strong>
<%= @catering.delivery_price %>
</p>

<p><strong>Offices:</strong>
<% @catering.offices.each do |f| %>
	<%= link_to f.title, office_path(f.id), class: 'btn btn-primary btn-xs' %>
<% end %>
</p>

<p><strong>Desription:</strong>
<%= @catering.description %>
</p>

<%= link_to 'List all caterings', caterings_path, class: 'btn btn-info' %>
<%= link_to 'Edit', edit_catering_path(@catering), class: 'btn btn-danger' %>

app/views/contacts/create.html.haml
.container
  %h1 Thank you for your message.
  %p We'll get back to you soon.

app/views/contacts/new.html.haml
%h1 Contact us
.row
	.col-lg-6
		.well
			= form_for @contact do |f|
				%fieldset
				.form-group
					= f.text_field :name, class: 'form-control', :placeholder => :title.capitalize
				.form-group
					= f.email_field :email, class: 'form-control', :placeholder => :email.capitalize
				.form-group
					= f.text_area :message, class: 'form-control', :placeholder => :message.capitalize
					= f.hidden_field(:nickname)
				.form-group
					= f.submit 'Submit', :class => 'btn btn-success'

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>


    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Food4u', root_path, class: "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <%= render 'layouts/navigation_links' %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <%= render 'layouts/navigation_links_right' %>
          </ul>
        </div><!--/.nav-coll
        apse -->
      </div>
    </div>

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav= render 'layouts/navigation_links'
/ Fixed navbar
.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Food4u', root_path, class: "navbar-brand"
    .navbar-collapse.collapse
      %ul.nav.navbar-nav= render 'layouts/navigation_links'
      %ul.nav.navbar-nav.navbar-right= render 'layouts/navigation_links_right'
    /
      \/.nav-coll
      apse

app/views/layouts/_navigation_links.html.erb
						<li><%= link_to "About", controller: "welcome" %></li>

            <li class="dropdown">
              <a href="" class="dropdown-toggle" data-toggle="dropdown">Offices<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "List all offices", controller: "offices" %></li>
                <li class="divider"></li>
                <li class="dropdown-header">Actions</li>
                <li><%= link_to "Create new office", new_office_path %></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="" class="dropdown-toggle" data-toggle="dropdown">Caterings<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "List all caterings", controller: "caterings" %></li>
                <li class="divider"></li>
                <li class="dropdown-header">Actions</li>
                <li><%= link_to "Create new catering", new_catering_path %></li>
              </ul>
            </li>

app/views/layouts/_navigation_links.html.haml
%li= link_to "About", controller: "welcome"
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", href: ""}
    Offices
    %b.caret
  %ul.dropdown-menu
    %li= link_to "List all offices", controller: "offices"
    %li.divider
    %li.dropdown-header Actions
    %li= link_to "Create new office", new_office_path
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", href: ""}
    Caterings
    %b.caret
  %ul.dropdown-menu
    %li= link_to "List all caterings", controller: "caterings"
    %li.divider
    %li.dropdown-header Actions
    %li= link_to "Create new catering", new_catering_path
%li= link_to "Users", controller: "users"
%li= link_to "Contact us", new_contact_path

app/views/layouts/_navigation_links_right.html.erb
            <li><%= link_to "Contact us", new_contact_path %></li>

app/views/layouts/_navigation_links_right.html.haml
- if user_signed_in?
  %li= link_to "#{current_user.username} (#{current_user.provider})", current_user.url
  %li= link_to "Sign out", destroy_user_session_path, :method => :delete
- if !user_signed_in?
  %li= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
  %li= link_to "Sign in with Vkontakte", user_omniauth_authorize_path(:vkontakte)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cook1" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Cook1" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/simplex.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Food4u" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "simplex", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>

<%= render 'layouts/navigation' %>
<br><br><br>


    <div class="container theme-showcase">
      <%= yield %>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "simplex" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>

app/views/layouts/simplex.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Food4u"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = stylesheet_link_tag "simplex", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)
  %body
    = render 'layouts/navigation'
    %br/
    %br/
    %br/
    .container.theme-showcase
      = yield
    / /container
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "simplex"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/offices/_form.html.erb
<%= form_for @office do |f| %>
  <% if @office.errors.any? %>
    
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Please fix: <%= pluralize(@office.errors.count, "error") %></h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @office.errors.full_messages.each do |msg| %>
            <li>
            <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

  <% end %>
	<p>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control input-sm' %>
  </p>

	<p>
    <%= f.label :adress %><br>
    <%= f.text_field :adress, class: 'form-control input-sm'  %>
  </p>

	<p>
    <%= f.label :phone %><br>
    <%= f.telephone_field :phone, class: 'form-control input-sm'  %>
  </p>

	<p>
    <%= f.label :email %><br>
    <%= f.email_field :email, class: 'form-control input-sm'  %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </p>

  <p>
    <%= f.label "Catering" %><br>
    <%= collection_select(:office, :catering_id, Catering.all, :id, :title) %>
  </p>

  <p>
    <%= link_to "Cancel", offices_path, class: 'btn btn-default'  %> 
    <%= f.submit 'Submit', :class => 'btn btn-success' %>
  </p>
<% end %>

app/views/offices/_form.html.haml
.row
  .col-lg-6
    .well
      = form_for @office, :html => { class: 'bs-example' } do |f|
        - if @office.errors.any?
          .panel.panel-primary
            .panel-heading
              %h3.panel-title
                Please fix: #{pluralize(@office.errors.count, "error")}
            .panel-body
              %ul
                - @office.errors.full_messages.each do |msg|
                  %li
                    = msg
        %fieldset
        .form-group
          = f.text_field :title, class: 'form-control input-sm', :placeholder => :title.capitalize
        .form-group
          = f.text_field :adress, class: 'form-control input-sm', :placeholder => :adress.capitalize
        .form-group
          = f.telephone_field :phone, class: 'form-control input-sm', :placeholder => :phone.capitalize
        .form-group
          = f.email_field :email, class: 'form-control input-sm', :placeholder => :email.capitalize
        .form-group
          = f.text_area :description, class: 'form-control', :placeholder => :description.capitalize
        .form-group
          = f.label "Please select Catering"
          = collection_select(:office, :catering_id, Catering.all, :id, :title, {}, {:class => 'form-control'})
        .form-group
          = link_to "Cancel", offices_path, class: 'btn btn-default'
          = f.submit 'Submit', :class => 'btn btn-success'

app/views/offices/edit.html.erb
<h1>Editing office</h1>

<%= render 'form' %>

app/views/offices/index.html.erb
<h1>All offices</h1>
<p align="right"><%= link_to "Create new office", new_office_path, class: 'btn btn-success' %></p>
<table width="100%">
	<% @offices.order("updated_at desc").each do |office| %>
		<tr>
			<td>
				<table width="100%">
					<tr>
						<td>
							<h3><%= link_to office.title, office %></h3>
							<strong>Contact:</strong>
							<%= office.adress %>, 
							<%= office.phone %>, 
							<%= office.email %><br>
							<strong>Catering:</strong> 
							<%= link_to office.catering.title, catering_path(office.catering) %>
						</td>
						<td width="150" align="right">
							<%= link_to 'Edit', edit_office_path(office), class: 'btn btn-danger' %>
							<%= link_to 'Delete', office_path(office), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
						</td>
					</tr>
				</table>
				<br>
				<br>
			</td>
		</tr>
	<% end %>
</table>

app/views/offices/new.html.erb
<h1>New Office</h1>

<%= render 'form' %>

app/views/offices/show.html.erb
<h1>Office "<%= @office.title %>"</h1>

<p><strong>Adress:</strong>
<%= @office.adress %>
</p>

<p><strong>Phone:</strong>
<%= @office.phone %>
</p>

<p><strong>Email:</strong>
<%= @office.email %>
</p>

<p><strong>Desription:</strong>
<%= @office.description %>
</p>

<p><strong>Catering:</strong>
<%= link_to @office.catering.title, catering_path(@office.catering) %>
</p>

<%= link_to 'List all offices', offices_path, class: 'btn btn-info' %>
<%= link_to 'Edit', edit_office_path(@office), class: 'btn btn-danger' %>

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :username
    = f.input :nickname
    = f.input :provider
    = f.input :url

  .form-actions
    = f.button :submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
- model_class = User.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:provider)
      %th= model_class.human_attribute_name(:sign_in_count)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.username, user.url
        %td= user.email
        %td= user.provider
        %td= user.sign_in_count
        %td= user.created_at
        %td
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @user.username
%p
  %b Nickname:
  = @user.nickname
%p
  %b Provider:
  = @user.provider
%p
  %b Url:
  = @user.url

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path